models/ProjetoAtividade.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "PROJETO_ATIVIDADE".
 *
 * @property double $ID_PROJETO_ATIVIDADE
 * @property string $DT_INICIO
 * @property string $DT_FIM
 * @property double $ID_ATIVIDADE
 * @property double $ID_PROJETO
 * @property string $STATUS
 * @property double $RESPONSAVEL
 *
 * @property ATIVIDADERESPONSAVEL[] $aTIVIDADERESPONSAVELs
 * @property ATUALIZACAOATIVIDADE[] $aTUALIZACAOATIVIDADEs
 * @property ATIVIDADE $1
 * @property PROJETO $10
 */
class ProjetoAtividade extends \yii\db\ActiveRecord
{
    var $TITULO;
    var $ATIVIDADE;
    var $RESPONSAVELLABEL;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'PROJETO_ATIVIDADE';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [                       
            [['ID_ATIVIDADE', 'ID_PROJETO', 'RESPONSAVEL'], 'number'],
            [['STATUS'], 'string', 'max' => 45],    
            [['DT_FIM', 'DT_INICIO'], 'safe'],            
            [['1'], 'exist', 'skipOnError' => true, 'targetClass' => ATIVIDADE::className(), 'targetAttribute' => ['1' => 'ID_ATIVIDADE']],
            [['1'], 'exist', 'skipOnError' => true, 'targetClass' => PROJETO::className(), 'targetAttribute' => ['1' => 'ID_PROJETO']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID_PROJETO_ATIVIDADE' => 'Id  Projeto  Atividade',
            'DT_INICIO' => 'Data  Inicio',
            'DT_FIM' => 'Data  Fim',
            'ID_ATIVIDADE' => 'Atividade',
            'ID_PROJETO' => 'Projeto',
            'STATUS' => 'Status',
            'RESPONSAVEL' => 'Responsavel',
            'RESPONSAVELLABEL' => 'Responsável',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getATIVIDADERESPONSAVELs()
    {
        return $this->hasMany(ATIVIDADERESPONSAVEL::className(), ['1' => 'ID_PROJETO_ATIVIDADE']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getATUALIZACAOATIVIDADEs()
    {
        return $this->hasMany(ATUALIZACAOATIVIDADE::className(), ['1' => 'ID_PROJETO_ATIVIDADE']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function get1()
    {
        return $this->hasOne(ATIVIDADE::className(), ['ID_ATIVIDADE' => '1']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function get10()
    {
        return $this->hasOne(PROJETO::className(), ['ID_PROJETO' => '1']);
    }
    
    public function getDescricaoAtividade(){
        return Atividade::findOne(['ID_ATIVIDADE'=> $this->ID_ATIVIDADE])->DC_ATIVIDADE;
    }

    public function getDTINICIO(){
        return Yii::$app->formatter->asDate($this->DT_INICIO, 'php:d/m/Y');
    }
    
    public function getDTFIM(){
        return Yii::$app->formatter->asDate($this->DT_FIM, 'php:d/m/Y');
    }
    
    public function getRESPONSAVEL(){
        $connection = Yii::$app->getDb("db2");
        $command = $connection->createCommand("SELECT "                    
                    . "                                     NM_USUARIO "
                    . "                                 FROM "
                    . "                                     BD_SICA.USUARIOS "
                    . "                                 WHERE "
                    . "                                     CD_USUARIO = ".$this->RESPONSAVEL."");                        
        $result = $command->queryAll();                              
        return ($result)?$result[0]['NM_USUARIO']:"";
    }
    
    public function getATIVIDADE(){
        return Atividade::findOne(['ID_ATIVIDADE' => $this->ID_ATIVIDADE])->DC_ATIVIDADE;
    }
}

controllers/ProjetoAtividadeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ProjetoAtividade;
use app\models\ProjetoAtividadeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;

/**
 * ProjetoAtividadeController implements the CRUD actions for ProjetoAtividade model.
 */
class ProjetoAtividadeController extends Controller
{
    /**
     * @inheritdoc
     */
    
    var $parametros;
    
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    
    public function beforeAction($action)
    {       
        $session = Yii::$app->session;                 
        if(!$session['logado']){
            return $this->redirect(['site/login']);
        }
        return true;
    }

    /**
     * Lists all ProjetoAtividade models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProjetoAtividadeSearch();                
        
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $session['atividades'] = null; 
        return $this->render('index', [
            'searchModel'           => $searchModel,
            'dataProvider'          => $dataProvider,            
        ]);
    }

    /**
     * Displays a single ProjetoAtividade model.
     * @param double $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProjetoAtividade model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProjetoAtividade();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID_PROJETO_ATIVIDADE]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionCreateMultiply($id)
    {                                        
        $array_providers = $this->prepara($id);        
        if ($array_providers['model']->load(Yii::$app->request->post())) {                                                
            $array_providers['model']->DT_INICIO   = new Expression("to_date('".implode('-', array_reverse(explode('/', $array_providers['model']->DT_INICIO)))."', 'yyyy-mm-dd')");
            $array_providers['model']->DT_FIM   = new Expression("to_date('".implode('-', array_reverse(explode('/', $array_providers['model']->DT_FIM)))."', 'yyyy-mm-dd')");
            if($array_providers['model']->save()){                
            }else{                
                exit;
            }            
            $model = new ProjetoAtividade();
            $model->ID_PROJETO = $id;
            $array_providers['model'] = $model;
            $array_providers['model']->DT_INICIO    = Yii::$app->formatter->asDate(date('d-m-Y'), 'php:d/m/Y');
            $array_providers['model']->DT_FIM       = Yii::$app->formatter->asDate(date('d-m-Y'), 'php:d/m/Y');
            return $this->render('createMultiply', $array_providers);
        } else {                        
            $array_providers['model']->DT_INICIO    = Yii::$app->formatter->asDate(date('d-m-Y'), 'php:d/m/Y');
            $array_providers['model']->DT_FIM       = Yii::$app->formatter->asDate(date('d-m-Y'), 'php:d/m/Y');
            return $this->render('createMultiply', $array_providers);
        }
    }
    
    public function actionSearch(){
        if (Yii::$app->request->isAjax) {              
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;        
            $data = Yii::$app->request->post();            
            $NM_USUARIO = explode(":", $data['NM_USUARIO'])[0];        
            if($NM_USUARIO != "" && $NM_USUARIO != null){                
                $connection = Yii::$app->getDb("db2");
                $command = $connection->createCommand("SELECT "
                    . "                                     CD_USUARIO, "
                    . "                                     NM_USUARIO "
                    . "                                 FROM "
                    . "                                     BD_SICA.USUARIOS "
                    . "                                 WHERE "
                    . "                                     upper(NM_USUARIO) LIKE ('%". strtoupper($NM_USUARIO)."%')");                        
                $result = $command->queryAll();                      
                
            }                                      
            $session = Yii::$app->session; 
            $session['usuarios'] = $result; 
            return "ok";
        }           
    }
    
    public function actionSearchClear(){
        if (Yii::$app->request->isAjax) {                                      
            $session = Yii::$app->session; 
            $session['usuarios'] = null;
            return "ok";
        }           
    }
    
    function filter($item) {
        $mailfilter = Yii::$app->request->getQueryParam('filteremail', '');
        if (strlen($mailfilter) > 0) {
            if (strpos($item['email'], $mailfilter) != false) {
                return true;
            } else {
                return false;
            }
        } else {
            return true;
        }
    }

    /**
     * Updates an existing ProjetoAtividade model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param double $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID_PROJETO_ATIVIDADE]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }        

    /**
     * Deletes an existing ProjetoAtividade model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param double $id
     * @return mixed
     */
    public function actionDelete($id, $idProjeto)
    {        
        $this->findModel($id)->delete();
        $array_providers = $this->prepara($idProjeto);        
        return $this->render('createMultiply', $array_providers);
    }

    /**
     * Finds the ProjetoAtividade model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param double $id
     * @return ProjetoAtividade the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProjetoAtividade::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionAdicionaAtividade()
    {        
        if (Yii::$app->request->isAjax) {                        
            $session = Yii::$app->session;                                    
            $atividade = $this->getAtividade(Yii::$app->request->post());               
            $this->adicionaAtividadeNaSessao($atividade, $session);
        }
    }
    
    function getAtividade($data){
        $ID_ATIVIDADE = explode(":", $data['ID_ATIVIDADE'])[0];                                  
        $projetoAtividade = new ProjetoAtividade();        
        $projetoAtividade->ID_ATIVIDADE = $ID_ATIVIDADE;                                    
        return $projetoAtividade;
    } 
    
    function adicionaAtividadeNaSessao($atividade, $session){                                 
        if (!isset($session['atividades']) || count($session['atividades'])==0){                                                
            $session['atividades'] = array($atividade);
        }else{
            if(!$this->existeNoArray($session['atividades'], $atividade->ID_ATIVIDADE)){                
                $arrayAtividades = $session['atividades'];
                $arrayAtividades[] = $atividade;                
                $this->array_sort_by_column($arrayAtividades, 'ID_ATIVIDADE');
                $session['atividades'] = $arrayAtividades;                                
            }
        }         
    }
    
    function existeNoArray($arrayAtividades, $id) {                        
        foreach($arrayAtividades as $val){                 
            if ($val['ID_ATIVIDADE'] === $id){                
                return true;
            }
        }
        return false;
    }
    
    function array_sort_by_column(&$arr, $col, $dir = SORT_ASC) {
        $sort_col = array();
        foreach ($arr as $key=> $row) {            
            $sort_col[$key] = $row[$col];
        }        
        array_multisort($sort_col, $dir, $arr);        
    } 
    
    function prepara($id){
        $model = new ProjetoAtividade();
        $model->ID_PROJETO = $id;
        $modelAtividade = new \app\models\Atividade();    
                
        $dataProviderAtividade = $this->getDataProviderAtividade();
        $providerUsuarios = $this->getProviderUsuarios();
        $providerAtividade = $this->getAtividadesProjeto();
                        
        $searchModel = new ProjetoAtividadeSearch(['ID_PROJETO' => $id]);                        
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination = ['pageSize' => 10];
        $dataProvider->sort->sortParam = false;
        
        return [                

views/projeto-atividade/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProjetoAtividade */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projeto-atividade-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'ID_PROJETO_ATIVIDADE')->textInput() ?>

    <?= $form->field($model, 'DT_INICIO')->textInput() ?>

    <?= $form->field($model, 'DT_FIM')->textInput() ?>

    <?= $form->field($model, 'ID_ATIVIDADE')->textInput() ?>

    <?= $form->field($model, 'ID_PROJETO')->textInput() ?>

    <?= $form->field($model, 'STATUS')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/projeto-atividade/_form_multiply.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Modelo */
/* @var $form yii\widgets\ActiveForm */
?>
<ul class="nav nav-tabs">    
    <li><?= Html::a('Projeto', ['/projeto/update', 'id' => $idProjeto]) ; ?>  </li>  
    <li><?= Html::a('Componentes', ['projeto/editar-componente', 'id' => $idProjeto]) ?></li>
    <li class="active"><a href="#">Atividades</a></li>
    <li><?= Html::a('Orçamentos', ['orcamento/create', 'id' => $idProjeto]) ?></li>    
</ul>
<div class="modelo-form">                  
    <?php $form = ActiveForm::begin(); ?> 
    <?= $form->field($model, 'ID_ATIVIDADE')->hiddenInput()->label(false) ?> 
    <?= $form->field($model, 'RESPONSAVEL')->hiddenInput()->label(false) ?>     
    <?php Pjax::begin(['id' => 'pjax-grid-view-atividades']); ?>            
        <table class="rwd-table">            
            <tr>
                <td colspan="3">                                   
                    <?= $form->field($model, 'ATIVIDADE')->textInput() ?>
                </td>
                <td style="vertical-align: top;">                    
                    <div class="form-group field-projetoatividade-id_atividade required has-error">
                        <label class="control-label">&nbsp;</label>                        
                        &nbsp;
                        <button type="button" class="form-control btn btn-primary glyphicon glyphicon-search" style="border: 0px solid;" data-toggle="modal" data-target="#modalAddAtividade">
                    </div>                                        
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <?= $form->field($model, 'RESPONSAVELLABEL')->textInput() ?>
                </td>
                <td style="vertical-align: top;">                    
                    <div class="form-group field-projetoatividade-id_atividade required has-error">
                        <label class="control-label">&nbsp;</label>                        
                        &nbsp;<button type="button" class="form-control btn btn-primary glyphicon glyphicon-search" style="border: 0px solid;" data-toggle="modal" data-target="#modalAddResponsavel">
                    </div>                                        
                </td>
            </tr>            
            <tr>
              <td>
                  <label>Data Início</label><br>
                    <?= DatePicker::widget([
                        'model' => $model,
                        'attribute' => 'DT_INICIO',
                        'language' => 'pt',
                        'dateFormat' => 'dd/MM/yyyy',                        
                    ]); ?>        
              <td>&nbsp;</td>
              <td>
                    <label>Data Término</label><br>                                        
                    <?= DatePicker::widget([
                        'model' => $model,
                        'attribute' => 'DT_FIM',
                        'language' => 'pt',                        
                        'dateFormat' => 'dd/MM/yyyy',
                    ]); ?>        
              </td>
            </tr>                        
          </table>
    <br>
    <?= Html::submitButton('Inserir' , ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>    
    <br><br>
    <?= GridView::widget([
        'dataProvider' => $dataProvider, 
        'emptyText' => 'Nenhuma atividade encontrada.',
        'summary'=>'',   
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],            
            [
                'attribute' => 'ID_ATIVIDADE',
                'filter' => false,                
                'format' => 'raw',
                'value' => function ($model) {
                    return  $model->getATIVIDADE();
                },
            ],
            [
                'attribute' => 'RESPONSAVEL',
                'filter' => false,                
                'format' => 'raw',
                'value' => function ($model) {
                    return  $model->getRESPONSAVEL();
                },
            ],
            [
                'attribute' => 'DT_INICIO',
                'filter' => false,                
                'format' => 'raw',
                'value' => function ($model) {
                    return  $model->getDTINICIO();
                },
            ],
            [
                'attribute' => 'DT_FIM',
                'filter' => false,                
                'format' => 'raw',
                'value' => function ($model) {
                    return  $model->getDTFIM();
                },
            ],
            // 'STATUS',            
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
                'buttons' => [
                    'delete' => function ($url2, $model) {                                                                
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['projeto-atividade/delete', "id"=>$model->ID_PROJETO_ATIVIDADE,"idProjeto"=>$model->ID_PROJETO], ['title' => 'Excluir', 'data-method' => 'POST']);
                    }                                     
                ],                            
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>                  

    <?php ActiveForm::end(); ?>

</div>
<?= $this->render('modalAddAtividade', [        
        'searchModelAtividade'      => $searchModelAtividade,
        'dataProvider'              => $dataProviderAtividade,    
        'modelAtividade'            => $modelAtividade,  
    ]);   
?> 
<?= 
    $this->render('modalAddResponsavel',[        
        'dataProviderUsuarios'      => $dataProviderUsuarios,                
        'modelAtividade'            => $modelAtividade,  
    ]);
?> 
<script type="text/javascript"> 
    function removerComponente(valor){
        var param = JSON.parse(valor);        
        
        $.ajax({
            url: '<?php echo Yii::$app->request->baseUrl. '/index.php?r=modelo/remove-componente' ?>',            
            type: 'post',   
            data: {
                 //ID_COMPONENTE: param.ID_COMPONENTE , 
                 TITULO: param.TITULO,
             },            
            success:function(data){
                console.log(data);
                $.pjax({container: '#pjax-grid-view-componentes'});                    
            }
        });
    }           
</script>

views/projeto-atividade/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProjetoAtividadeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projeto-atividade-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID_PROJETO_ATIVIDADE') ?>

    <?= $form->field($model, 'DT_INICIO') ?>

    <?= $form->field($model, 'DT_FIM') ?>

    <?= $form->field($model, 'ID_ATIVIDADE') ?>

    <?= $form->field($model, 'ID_PROJETO') ?>

    <?php // echo $form->field($model, 'STATUS') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/projeto-atividade/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ProjetoAtividade */

$this->title = 'Create Projeto Atividade';
$this->params['breadcrumbs'][] = ['label' => 'Projeto Atividades', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projeto-atividade-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/projeto-atividade/createMultiply.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ProjetoAtividade */

$this->title = 'Adicionar Atividades';
$this->params['breadcrumbs'][] = ['label' => 'Projetos', 'url' => ['/projeto']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projeto-atividade-create">    

    <?= $this->render('_form_multiply', [
        'model'                     => $model,
        'searchModelAtividade'      => $searchModelAtividade,
        'dataProviderAtividade'     => $dataProviderAtividade,    
        'modelAtividade'            => $modelAtividade,  
        'providerAtividade'         => $providerAtividade,
        'idProjeto'                 => $idProjeto,
        'dataProviderUsuarios'      => $dataProviderUsuarios,                
        'dataProvider'              => $dataProvider,        
    ]) ?>

</div>

views/projeto-atividade/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjetoAtividadeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Projeto Atividades';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projeto-atividade-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Projeto Atividade', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'ID_PROJETO_ATIVIDADE',
            'DT_INICIO',
            'DT_FIM',
            'ID_ATIVIDADE',
            'ID_PROJETO',
            // 'STATUS',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/projeto-atividade/modalAddResponsavel.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\widgets\Pjax;

?>  
<!-- Modal -->
<div class="modal fade bs-example-modal-lg" tabindex="-1" id="modalAddResponsavel" role="dialog" aria-labelledby="Adicionar Responsavel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Selecionar Responsável</h4>
            </div>            
            <div class="modal-body">
                <?php $form = ActiveForm::begin(); ?>
                <div style="width:100%;height: 40px;">                    
                        <div style="width:70%;float: left;">
                            <input type="text" id="NM_USUARIO" style="width: 100%;">
                        </div>                    
                        <div style="width:1%;float: left;height: 1px;">                            
                        </div>
                        <div style="width:9%;float: left;">                                  
                            <?= Html::button('Pesquisar', ['class' => 'btn btn-success', "id" => "pesquisar"]) ?>                                                
                        </div>                                                   
                </div> 
                <?php ActiveForm::end(); ?>
                <?php Pjax::begin(['id' => 'pjax-grid-view-responsavel','timeout' => 50000]); ?>
                <?= GridView::widget([
                    'dataProvider' => $dataProviderUsuarios,                                        
                    'summary' => '',
                    'columns' => [                                  
                        [
                            "attribute" => "Usuario",                            
                            'value' => 'NM_USUARIO',
                            'headerOptions' => ['style' => 'width:80%'],                            
                        ],
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{delete}',                                                        
                            'buttons' => [
                                'delete' => function ($model, $key) { 
                                    return Html::button(' Selecionar', ['value' => json_encode(array('CD_USUARIO' => $key['CD_USUARIO'], 'NM_USUARIO' => $key['NM_USUARIO'])), 'class' => 'btn btn-primary btn-sm glyphicon glyphicon-check', 'onclick'=>'selecionarResponsavel(value)']);
                                }                                     
                            ],                            
                        ],                      
                    ],
                ]); ?>
                <?php Pjax::end(); ?>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                 
            </div>
    </div>
  </div>
</div>
<script type="text/javascript">       
    function selecionarResponsavel(valor){
        var param = JSON.parse(valor);        
        $('#projetoatividade-responsavellabel').val(param.NM_USUARIO);
        $('#projetoatividade-responsavel').val(param.CD_USUARIO);       
        $('#modalAddResponsavel').modal('toggle');   
        $.ajax({
            url: '<?php echo Yii::$app->request->baseUrl. '/index.php?r=projeto-atividade/search-clear' ?>',            
            type: 'post',                           
            success:function(data){                                                
                $.pjax.reload({                                
                    container:"#pjax-grid-view-responsavel",
                    async: false
               }); 
            }
        });
    }
</script>
<script type="text/javascript">   
    var fac= document.getElementById("pesquisar");    
        
    fac.onclick = function fun(){                               
        
        $.ajax({
            url: '<?php echo Yii::$app->request->baseUrl. '/index.php?r=projeto-atividade/search' ?>',            
            type: 'post',               
            data: {
                 NM_USUARIO: $("#NM_USUARIO").val() ,                                   
            },            
            success:function(data){                                
               $.pjax.reload({                                
                    container:"#pjax-grid-view-responsavel",
                    async: false
               }); 
            }
        });
    };
        
</script>

views/projeto-atividade/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ProjetoAtividade */

$this->title = 'Update Projeto Atividade: ' . $model->ID_PROJETO_ATIVIDADE;
$this->params['breadcrumbs'][] = ['label' => 'Projeto Atividades', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ID_PROJETO_ATIVIDADE, 'url' => ['view', 'id' => $model->ID_PROJETO_ATIVIDADE]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="projeto-atividade-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/projeto-atividade/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ProjetoAtividade */

$this->title = $model->ID_PROJETO_ATIVIDADE;
$this->params['breadcrumbs'][] = ['label' => 'Projeto Atividades', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projeto-atividade-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->ID_PROJETO_ATIVIDADE], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->ID_PROJETO_ATIVIDADE], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'ID_PROJETO_ATIVIDADE',
            'DT_INICIO',
            'DT_FIM',
            'ID_ATIVIDADE',
            'ID_PROJETO',
            'STATUS',
        ],
    ]) ?>

</div>