models/Projeto.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "PROJETO".
 *
 * @property double $ID_PROJETO
 * @property double $ID_MODELO
 * @property double $DT_CADASTRO
 * @property string $LOGIN_CADASTRO
 * @property string $TITULO
 * @property integer $STATUS
 * @property string $DT_APROVACAO
 * @property string $LOGIN_APROVACAO
 * @property string $DT_INICIO
 * @property string $DT_TERMINO
 * @property string $PERIODO
 * @property string $RESPONSAVEL
 *
 * @property ORCAMENTO[] $oRCAMENTOs
 * @property MODELO $1
 * @property PROJETOATIVIDADE[] $pROJETOATIVIDADEs
 * @property PROJETOCOMPONENTE[] $pROJETOCOMPONENTEs
 */
class Projeto extends \yii\db\ActiveRecord
{    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'PROJETO';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID_MODELO', 'TITULO'], 'required'],
            [['ID_PROJETO', 'ID_MODELO', 'DT_CADASTRO'], 'number'],
            [['STATUS'], 'integer'],
            [['DT_APROVACAO', 'RESPONSAVEL'], 'string'],
            [['LOGIN_CADASTRO', 'LOGIN_APROVACAO'], 'string', 'max' => 20],
            [['TITULO'], 'string', 'max' => 100],
            [['PERIODO'], 'string', 'max' => 7],
            [['DESCRICAO'], 'string', 'max' => 150],
            [['SUBTITULO'], 'string', 'max' => 50],
            [['RESPONSAVEL'], 'string', 'max' => 255],
            [['1'], 'exist', 'skipOnError' => true, 'targetClass' => MODELO::className(), 'targetAttribute' => ['1' => 'ID_MODELO']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID_PROJETO' => 'Código',
            'ID_MODELO' => 'Modelo',
            'DT_CADASTRO' => 'Data Cadastro',
            'LOGIN_CADASTRO' => 'Login Cadastro',
            'TITULO' => 'Título',
            'STATUS' => 'Status',
            'DT_APROVACAO' => 'Data Aprovacao',
            'LOGIN_APROVACAO' => 'Login  Aprovacao',
            'DT_INICIO' => 'Data de Inicio',
            'DT_TERMINO' => 'Data de Término',
            'PERIODO' => 'Periodo',
            'RESPONSAVEL' => 'Responsável',
            'DESCRICAO' => 'Descrição',
            'SUBTITULO' => 'Subtítulo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getORCAMENTOs()
    {
        return $this->hasMany(ORCAMENTO::className(), ['1' => 'ID_PROJETO']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function get1()
    {
        return $this->hasOne(MODELO::className(), ['ID_MODELO' => '1']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPROJETOATIVIDADEs()
    {
        return $this->hasMany(PROJETOATIVIDADE::className(), ['1' => 'ID_PROJETO']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPROJETOCOMPONENTEs()
    {
        return $this->hasMany(PROJETOCOMPONENTE::className(), ['1' => 'ID_PROJETO']);
    }
    
    public function getComponentes() {
        return $this->hasMany(Componente::className(), ['ID_COMPONENTE' => 'COMPONENTE_ID_COMPONENTE'])
          ->viaTable('PROJETO_COMPONENTE', ['PROJETO_ID_PROJETO' => 'ID_PROJETO']);
    }
    
    public function getModelo(){    	
        $modelo = Modelo::findOne(['ID_MODELO'=> $this->ID_MODELO])->DC_MODELO;        
        return $modelo;        
    }
}

controllers/ProjetoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Projeto;
use app\models\ProjetoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Modelo;
use app\models\ProjetoComponente;
use yii\db\Expression;


/**
 * ProjetoController implements the CRUD actions for Projeto model.
 */
class ProjetoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    
    public function beforeAction($action)
    {       
        $session = Yii::$app->session;                 
        if(!$session['logado']){
            return $this->redirect(['site/login']);
        }
        return true;
    }

    /**
     * Lists all Projeto models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProjetoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Projeto model.
     * @param double $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Projeto model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Projeto();
        if($model->load(Yii::$app->request->post())){            
            //$model->DT_INICIO = new Expression("to_date('" . $model->DT_INICIO . "','yyyy-mm-dd')");
            //$model->DT_INICIO   = 'to_date("'.$model->DT_INICIO.'", "yyyy-mm-dd")';
            //$model->DT_TERMINO  = "to_date('".$model->DT_TERMINO."', 'yyyy-mm-dd')";
            if ($model->save()) {
                $componentes = [];
                $modelo = Modelo::findOne(['ID_MODELO'=>$model->ID_MODELO]);   
                $modeloComponentes = $this->array_sort_by_column($modelo->mODELOCOMPONENTEs, "CODIGO");
                foreach($modeloComponentes as $modeloComponente){                                                                              
                    $projetoComponente = new ProjetoComponente();
                    $projetoComponente->COMPONENTE_ID_COMPONENTE = $modeloComponente->ID_COMPONENTE;
                    $componente = \app\models\Componente::findOne(['ID_COMPONENTE'=>$modeloComponente->ID_COMPONENTE]);                        
                    $projetoComponente->TITULO = $componente->TITULO;
                    $projetoComponente->CODIGO = $modeloComponente->CODIGO;
                    $projetoComponente->PROJETO_ID_PROJETO = $model->ID_PROJETO;
                    $projetoComponente->save();                
                    $componentes[] = $projetoComponente;
                }                          
                return $this->render('componentes', [
                    'model' => $model,
                    'componentes' => $componentes,
                ]);
            }
        }else {
            return $this->render('create', [
                'model' => $model,                
            ]);
        }
    }   

    /**
     * Updates an existing Projeto model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param double $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID_PROJETO]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Projeto model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param double $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Projeto model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param double $id
     * @return Projeto the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Projeto::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionAdicionaComponente()
    {        
        if (Yii::$app->request->isAjax) {                                                          
            $data = Yii::$app->request->post();                          
            foreach ($data['myData'] as $valor){
                reset($valor);
                $key = key($valor);    
                $projetoComponente = ProjetoComponente::findOne(['ID_PROJETO_COMPONENTE' => $key]);
                $projetoComponente->DESCRICAO = $valor[$key];
                $projetoComponente->update();
            }
        }
    }
    
    public function actionGerarPdf($id)
    {                        
        require_once '..\vendor\autoload.php';                
        $mpdf = new \Mpdf\Mpdf();     
        $model = $this->findModel($id);
        $projetoComponente = ProjetoComponente::findAll(['PROJETO_ID_PROJETO' => $id]);
        $projetoComponente = $this->array_sort_by_column($projetoComponente, "CODIGO");        
        $mpdf->WriteHTML($this->getCapa($projetoComponente, $model));
        $mpdf->WriteHTML('<pagebreak suppress="off" />');
        $mpdf->WriteHTML('<pagebreak suppress="off" />');                   
        $mpdf->WriteHTML($this->getContraCapa($projetoComponente, $model));
        $mpdf->WriteHTML('<pagebreak suppress="off" />');
        $mpdf->WriteHTML('<pagebreak suppress="off" />');                
        $mpdf->WriteHTML($this->getSumario($projetoComponente));
        $mpdf->WriteHTML('<pagebreak suppress="off" />');
        $mpdf->setFooter('{PAGENO}');  
        $cont = 1;
        $qtdLinhas = 0;        
        foreach($projetoComponente as $componente){                                                            
            $html = "";                    
            $qtdLinhas = $this->quebraLinha($componente->CODIGO, $cont, $mpdf, $qtdLinhas);            
            echo $componente->TITULO." - ".$qtdLinhas."<br>";                        
            $negritoIni = "";$negritoFim = "";$brs = "";
            if(!strpos($componente->CODIGO, '.')){
                $qtdLinhas = $this->getNumeroLinhas($componente->DESCRICAO);
                $negritoIni = "<b>";
                $negritoFim = "</b>";
                $brs = "<br>";                
            }else{
                $qtdLinhas = $this->getNumeroLinhas($componente->DESCRICAO)+$qtdLinhas;
                $brs = "";
            }
            $html .= $brs."
                <p style='font-size: 22px;'>".
                            $negritoIni.$componente->CODIGO." ".$componente->TITULO.$negritoFim.
                            "</p>".$brs;
            $html .= $componente->DESCRICAO;
            $mpdf->WriteHTML($html); 
            $cont++;
        }
        $projetoAtividades = \app\models\ProjetoAtividade::findAll(['ID_PROJETO' => $id]);        
        $mpdf->WriteHTML('<pagebreak suppress="off" />');
        $mpdf->WriteHTML($this->getAtividades($projetoAtividades));
        $mpdf->WriteHTML('<pagebreak suppress="off" />');
        $mpdf->WriteHTML($this->getResponsabilidades($projetoAtividades));        
        $mpdf->setFooter('{PAGENO}'); 
        $mpdf->Output();        
    }
    
    public function actionEditarComponente($id)
    {
        $model = $this->findModel($id);
                
        $componentes = ProjetoComponente::findAll(['PROJETO_ID_PROJETO'=>$id]);                        
        $componentes = $this->array_sort_by_column($componentes, "CODIGO");
        return $this->render('componentes', [
            'model' => $model,
            'componentes' => $componentes,
        ]);        
    } 
    
    function quebraLinha($codigo, $pagina, $mpdf, $linhas){
        if(!strpos($codigo, '.')){            
            $mpdf->WriteHTML(($pagina > 1)?'<pagebreak suppress="off" />':"");            
            $linhas = 0;
        }else{
            if($linhas>20){
                $mpdf->WriteHTML(($pagina > 1)?'<pagebreak suppress="off" />':"");
                $linhas = 0;
            }
        }
        return $linhas;
    }
    
    function getNumeroLinhas($string){
        $descricao = str_replace('&nbsp; ', '', $string);
        $descricao = str_replace('&nbsp;', '', $descricao);
        $qtdLinhas = floor(strlen(strip_tags($descricao))/70);
        $qtdBr = substr_count($string, '<br>');
        $qtdP = substr_count($string, '<p>');
        $qtdLinhas +=($qtdBr > $qtdP)? $qtdBr : $qtdP;
        $qtdLinhas += substr_count($string, '<li>');
        return $qtdLinhas;
    }
    
    function getCapa($projetoComponente, $model){        
        $html = '<style> 
                    .test{                                                 
                        background:url(http://localhost'.\yii\helpers\Url::to('@web/css/dot.jpg').') repeat-x;                                                
                    }
                 </style>';
        
        $html .= "                
                <br><br><br><br>                
                <table width='100%'>

views/projeto/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Modelo;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Projeto */
/* @var $form yii\widgets\ActiveForm */
?>
<ul class="nav nav-tabs" <?= $model->isNewRecord ? 'style="display:none;"' : '' ?>>
  <li class="active"><a href="#">Projeto</a></li>
  <li><?= Html::a('Componentes', ['/projeto/editar-componente', 'id' => $model->ID_PROJETO]) ; ?>  </li>
  <li><?= Html::a('Atividades', ['projeto-atividade/create-multiply', 'id' => $model->ID_PROJETO]) ?></li>  
  <li><?= Html::a('Orçamentos', ['orcamento/create', 'id' => $model->ID_PROJETO]) ?></li>    
</ul>
<br>
<div class="projeto-form">

    <?php $form = ActiveForm::begin(); ?>    
    <div style="width:50%; margin-right:5%;">
        <?= $form->field($model, 'ID_MODELO')->dropDownList(
                ArrayHelper::map(Modelo::find()->all(),'ID_MODELO', 'DC_MODELO')
            );
        ?>

        <?= $form->field($model, 'TITULO')->textInput(['maxlength' => true]) ?>
        
        <?= $form->field($model, 'SUBTITULO')->textInput(['maxlength' => true]) ?>
        
        <?= $form->field($model, 'DESCRICAO')->textarea(['rows' => '3', 'maxlength' => true]) ?>
            
        <?= $form->field($model, 'RESPONSAVEL')->textInput(['maxlength' => true]) ?>                

        <label>Data Início</label><br>
        <?= DatePicker::widget([
            'model' => $model,
            'attribute' => 'DT_INICIO',
            'language' => 'pt',
            'dateFormat' => 'dd/MM/yyyy',
        ]); ?>                
        <br><br>
        <label>Data Término</label><br>
        <?= DatePicker::widget([
            'model' => $model,
            'attribute' => 'DT_TERMINO',
            'language' => 'pt',
            'dateFormat' => 'dd/MM/yyyy',
        ]); ?>           
        <br><br>
        <table>
            <tr>
                <td>
                    <div class="form-group">
                        <?= Html::submitButton($model->isNewRecord ? 'Criar' : 'Alterar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    </div>
                </td>                                
            </tr>
        </table>
    </div>       

    <?php ActiveForm::end(); ?>

</div>

views/projeto/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProjetoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projeto-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID_PROJETO') ?>

    <?= $form->field($model, 'ID_MODELO') ?>

    <?= $form->field($model, 'DT_CADASTRO') ?>

    <?= $form->field($model, 'LOGIN_CADASTRO') ?>

    <?= $form->field($model, 'TITULO') ?>

    <?php // echo $form->field($model, 'STATUS') ?>

    <?php // echo $form->field($model, 'DT_APROVACAO') ?>

    <?php // echo $form->field($model, 'LOGIN_APROVACAO') ?>

    <?php // echo $form->field($model, 'DT_INICIO') ?>

    <?php // echo $form->field($model, 'DT_TERMINO') ?>

    <?php // echo $form->field($model, 'PERIODO') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/projeto/aprovacao.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjetoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Projetos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projeto-index">       
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'emptyText' => 'Nenhum projeto cadastrado.',
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],                        
            [
                'attribute' => 'MODELO',
                'filter' => false,                
                'format' => 'raw',
                'value' => function ($model) {
                    return  $model->getModelo();
                },
            ],
            'TITULO',
            'STATUS',
            // 'DT_APROVACAO',
            // 'LOGIN_APROVACAO',
            // 'DT_INICIO',
            // 'DT_TERMINO',
            // 'PERIODO',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{aprovar} {reprovar} {visualizar}',
                'buttons' => [
                    'aprovar' => function ($url2, $model) {                                                                                        
                        return Html::a('<span class="btn btn-success btn-sm glyphicon glyphicon-check"></span>', 'index.php?r=projeto/gerar-pdf&id='.$model->ID_PROJETO, ['title' => 'Aprovar']);
                    },             
                    'reprovar' => function ($url2, $model) {                                                                                        
                        return Html::a('<span class="btn btn-danger btn-sm glyphicon glyphicon-remove"></span>', 'index.php?r=projeto/gerar-pdf&id='.$model->ID_PROJETO, ['title' => 'Não aprovar']);
                    },                    
                    'visualizar' => function ($url2, $model) {                                                
                        return Html::a('', ['/projeto/gerar-pdf', 'id' => $model->ID_PROJETO], ['target' => '_blank', 'class'=>'btn btn-primary btn-sm glyphicon glyphicon-eye-open']) ; 
                    },
                    
                ],                            
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/projeto/componentes.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditorInline;

/* @var $this yii\web\View */
/* @var $model app\models\Projeto */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'Editor de componentes';
$this->params['breadcrumbs'][] = ['label' => 'Projetos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<style>
.sumario{  
  list-style-type: none;
}
.dot-div {
  border-bottom: thin dashed gray;
  width: 100%;
  height: 14px
}
.text-div {
  margin-top: -14px
}
.text-span {
  background: #fff;
  padding-right: 5px
}
.pull-right {
  float: right;
  padding-left: 5px
}
</style>
<ul class="nav nav-tabs">
  <li><?= Html::a('Projeto', ['update', 'id' => $model->ID_PROJETO]) ?></li>
  <li class="active"><a href="#">Componentes</a></li>
  <li><?= Html::a('Atividades', ['projeto-atividade/create-multiply', 'id' => $model->ID_PROJETO]) ?></li>
  <li><?= Html::a('Orçamentos', ['orcamento/create', 'id' => $model->ID_PROJETO]) ?></li>    
</ul>
<br>
<div class="projeto-form">        
    <?php $form = ActiveForm::begin(); ?>    
    <div style="width:60%; margin-right:5%;">        
    <div>
        <label id="capa_toogle">+ Capa</label>        
        <div id="capa_content" style="display: none; background: #fff; border: 1px solid silver;">
            <center>
                <br><br>
                <p style="font-size: 22px;"><b>SÉCULO MANAUS </b></p>
                <br><br><br><br><br>
                <br>                
                <p style="font-size: 18px;"><?php echo $model->RESPONSAVEL; ?> </p>
                <br><br><br><br><br>
                <br><br><br><br><br>                
                <br>
                <p style="font-size: 24px;"><strong><?php echo $model->TITULO; ?> </strong></p>
                <br><br><br><br><br>
                <br><br><br><br><br>
                <br><br><br>
                <p style="font-size: 20px;"><b>Manaus, AM </b></p>
                <p style="font-size: 20px;"><b><?php echo date("Y"); ?> </b></p>
                <br><br><br>
            </center>            
        </div>
    </div> 
    <br>
    <div>
        <label id="sumario_toogle">+ Sumário</label>        
        <div id="sumario_content" style="display: none; background: #fff; border: 1px solid silver;">
            <center>
                <br><br>
                <p style="font-size: 22px;"><b>SUMÁRIO </b></p>
                <br>            
            </center>
            <ul style="width:93%;" class="sumario">
                    <?php 
                    foreach($componentes as $componente){
                    ?>
                        <li>
                            <div class="dot-div"></div>
                            <div class="text-div">
                              <?php 
                              if(!strpos($componente->CODIGO, '.')){                                                                
                              ?>
                                <span class="text-span"><b><?php echo $componente->CODIGO." "."$componente->TITULO" ?></b></span>
                              <?php
                              }else{
                              ?>
                                <span class="text-span"><?php echo $componente->CODIGO." "."$componente->TITULO" ?></span>
                              <?php 
                              }
                              ?>                                
                              <span class="text-span pull-right">x</span>
                            </div>
                        </li>
                    <?php 
                    }
                    ?>                     
            </ul>
            <br><br><br><br><br><br>
            <br><br><br><br><br><br>                
            <br><br><br><br><br>
            <br><br><br><br><br>                       
        </div>
    </div> 
    <div id="componentsform">
        <?php 
        foreach($componentes as $componente){                                       
        ?>    
        <br>
                <label id="capa_toogle_<?php echo $componente->ID_PROJETO_COMPONENTE; ?>" 
                       onclick="tootleDimanic(<?php echo $componente->ID_PROJETO_COMPONENTE; ?>, 
                                              '<?php echo $componente->CODIGO." ".$componente->TITULO; ?>');">+ <?php echo $componente->CODIGO." ".$componente->TITULO; ?></label>
                <div id="capa_content_<?php echo $componente->ID_PROJETO_COMPONENTE; ?>" style="display: none;background: #fff; border: 1px solid silver;padding: 0px;">
                    <?php CKEditorInline::begin(['preset' => 'basic', 'id' => $componente->ID_PROJETO_COMPONENTE]);
                        if($componente->DESCRICAO){
                            echo $componente->DESCRICAO;
                        }else{
                            echo "<br>&nbsp;&nbsp;&nbsp;Clique aqui para editar ".$componente->TITULO."<br><br><br>";
                        }                        
                    CKEditorInline::end();?>
                </div>            
            <br>
        <?php 

        }

        ?>       
    </div>
    <br>
    <div style="margin-left: 10px;margin-right: 10px;">
        <div class="alert alert-success" id="message-success" style="display: none;">                    
            <strong>As alterações foram salvas.</strong>
        </div>
        <div class="alert alert-danger fade in" id="message-error" style="display: none;">                    
            <strong>Erro!</strong> Já existe um componente com esse título.
        </div>  
    </div>
    <table>
        <tr>
            <td>
                <div class="form-group">            
                    <?= Html::button('Salvar Alterações', ['class' => 'btn btn-success', "id" => "salvar"]) ?>  
                </div>
            </td>
            <td>&nbsp;</td>
            <td>
                <div class="form-group">            
                    <?= Html::a('Visualizar Documento', ['/projeto/gerar-pdf', 'id' => $model->ID_PROJETO], ['target' => '_blank', 'class'=>'btn btn-primary']) ; ?>  
                </div>
            </td>
        </tr>
    </table>                
    </div>       

    <?php ActiveForm::end(); ?>

</div>

<script type="text/javascript">   
    var fac= document.getElementById("salvar");
    var visualizar= document.getElementById("visualizar");
    var capa= document.getElementById("capa_toogle");
    var sumario= document.getElementById("sumario_toogle");
    
    var jsonObj = [];    
    fac.onclick = function fun(){               
        $('#componentsform > div').children('.cke_editable').each(function () {
            console.log("tetas");
            componente = {};
            componente[this.id] = this.innerHTML;
            jsonObj.push(componente);
        }); 
        console.log(jsonObj);
        $.ajax({
            url: '<?php echo Yii::$app->request->baseUrl. '/index.php?r=projeto/adiciona-componente' ?>',            
            type: 'post',               
            data: {myData: jsonObj},
            beforeSend: function(){
                
            },
            success:function(data){
                $("#message-success").show();
                    setTimeout(function(){
                        $('#message-success').fadeOut("slow");
                }, 2000);
            }
        });
    };
    
    capa.onclick = function funCapa(){               
        this.innerHTML = (this.innerHTML == "+ Capa")?"- Capa":"+ Capa";
        $('#capa_content').slideToggle("slow");
    };
    
    sumario.onclick = function funSumario(){                       
        this.innerHTML = (this.innerHTML.indexOf('+') > -1)?"- Sumário":"+ Sumário";
        $('#sumario_content').slideToggle("slow");
    };
    
    function tootleDimanic(id, titulo){        
        var titulo_capa= document.getElementById("capa_toogle_"+id);        
        titulo_capa.innerHTML = (titulo_capa.innerHTML == "+ "+titulo) ? "- "+titulo : "+ "+titulo;
        $('#capa_content_'+id).slideToggle("slow");
    }
        
</script>

views/projeto/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Projeto */

$this->title = 'Criar Projeto';
$this->params['breadcrumbs'][] = ['label' => 'Projetos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projeto-create">    

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/projeto/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Projeto */

$this->title = 'Atualizar Projeto: ' . $model->TITULO;
$this->params['breadcrumbs'][] = ['label' => 'Projetos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ID_PROJETO, 'url' => ['view', 'id' => $model->ID_PROJETO]];
$this->params['breadcrumbs'][] = 'Atualizar';
?>
<div class="projeto-update">    

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>